; GET
[StateDef 4401]
type    = S
movetype= I
physics = N
anim = 9741
ctrl = 0

[State Choose what to display wisely]
type = Null
triggerall = time = 0
trigger1 = (parent,var(40) & floor(exp(0*ln(2)) + 0.5) )
trigger1 = !(parent,var(50) & floor(exp(0*ln(2)) + 0.5) )
trigger1 = (var(10) := 0)
trigger2 = (parent,var(40) & floor(exp(1*ln(2)) + 0.5) )
trigger2 = !(parent,var(50) & floor(exp(1*ln(2)) + 0.5) )
trigger2 = (var(10) := 1)
trigger3 = (parent,var(40) & floor(exp(2*ln(2)) + 0.5) )
trigger3 = !(parent,var(50) & floor(exp(2*ln(2)) + 0.5) )
trigger3 = (var(10) := 2)
trigger4 = (parent,var(40) & floor(exp(3*ln(2)) + 0.5) )
trigger4 = !(parent,var(50) & floor(exp(3*ln(2)) + 0.5) )
trigger4 = (var(10) := 3)
trigger5 = (parent,var(40) & floor(exp(4*ln(2)) + 0.5) )
trigger5 = !(parent,var(50) & floor(exp(4*ln(2)) + 0.5) )
trigger5 = (var(10) := 4)
trigger6 = (parent,var(40) & floor(exp(5*ln(2)) + 0.5) )
trigger6 = !(parent,var(50) & floor(exp(5*ln(2)) + 0.5) )
trigger6 = (var(10) := 5)
trigger7 = (parent,var(40) & floor(exp(6*ln(2)) + 0.5) )
trigger7 = !(parent,var(50) & floor(exp(6*ln(2)) + 0.5) )
trigger7 = (var(10) := 6)
trigger8 = (parent,var(40) & floor(exp(7*ln(2)) + 0.5) )
trigger8 = !(parent,var(50) & floor(exp(7*ln(2)) + 0.5) )
trigger8 = (var(10) := 7)
trigger9 = (parent,var(40) & floor(exp(8*ln(2)) + 0.5) )
trigger9 = !(parent,var(50) & floor(exp(8*ln(2)) + 0.5) )
trigger9 = (var(10) := 8)
trigger10 = (parent,var(40) & floor(exp(9*ln(2)) + 0.5) )
trigger10 = !(parent,var(50) & floor(exp(9*ln(2)) + 0.5) )
trigger10 = (var(10) := 9)
[State Choose what to display wisely]
type = Null
triggerall = time = 0
trigger1 = (parent,var(41) & floor(exp(0*ln(2)) + 0.5) )
trigger1 = !(parent,var(51) & floor(exp(0*ln(2)) + 0.5) )
trigger1 = (var(10) := 10)
trigger2 = (parent,var(41) & floor(exp(1*ln(2)) + 0.5) )
trigger2 = !(parent,var(51) & floor(exp(1*ln(2)) + 0.5) )
trigger2 = (var(10) := 11)
trigger3 = (parent,var(41) & floor(exp(2*ln(2)) + 0.5) )
trigger3 = !(parent,var(51) & floor(exp(2*ln(2)) + 0.5) )
trigger3 = (var(10) := 12)
trigger4 = (parent,var(41) & floor(exp(3*ln(2)) + 0.5) )
trigger4 = !(parent,var(51) & floor(exp(3*ln(2)) + 0.5) )
trigger4 = (var(10) := 13)
trigger5 = (parent,var(41) & floor(exp(4*ln(2)) + 0.5) )
trigger5 = !(parent,var(51) & floor(exp(4*ln(2)) + 0.5) )
trigger5 = (var(10) := 14)
trigger6 = (parent,var(41) & floor(exp(5*ln(2)) + 0.5) )
trigger6 = !(parent,var(51) & floor(exp(5*ln(2)) + 0.5) )
trigger6 = (var(10) := 15)
trigger7 = (parent,var(41) & floor(exp(6*ln(2)) + 0.5) )
trigger7 = !(parent,var(51) & floor(exp(6*ln(2)) + 0.5) )
trigger7 = (var(10) := 16)
trigger8 = (parent,var(41) & floor(exp(7*ln(2)) + 0.5) )
trigger8 = !(parent,var(51) & floor(exp(7*ln(2)) + 0.5) )
trigger8 = (var(10) := 17)
trigger9 = (parent,var(41) & floor(exp(8*ln(2)) + 0.5) )
trigger9 = !(parent,var(51) & floor(exp(8*ln(2)) + 0.5) )
trigger9 = (var(10) := 18)
trigger10 = (parent,var(41) & floor(exp(9*ln(2)) + 0.5) )
trigger10 = !(parent,var(51) & floor(exp(9*ln(2)) + 0.5) )
trigger10 = (var(10) := 19)
[State Choose what to display wisely]
type = Null
triggerall = time = 0
trigger1 = (parent,var(42) & floor(exp(0*ln(2)) + 0.5) )
trigger1 = !(parent,var(52) & floor(exp(0*ln(2)) + 0.5) )
trigger1 = (var(10) := 20)
trigger2 = (parent,var(42) & floor(exp(1*ln(2)) + 0.5) )
trigger2 = !(parent,var(52) & floor(exp(1*ln(2)) + 0.5) )
trigger2 = (var(10) := 21)
trigger3 = (parent,var(42) & floor(exp(2*ln(2)) + 0.5) )
trigger3 = !(parent,var(52) & floor(exp(2*ln(2)) + 0.5) )
trigger3 = (var(10) := 22)
trigger4 = (parent,var(42) & floor(exp(3*ln(2)) + 0.5) )
trigger4 = !(parent,var(52) & floor(exp(3*ln(2)) + 0.5) )
trigger4 = (var(10) := 23)
trigger5 = (parent,var(42) & floor(exp(4*ln(2)) + 0.5) )
trigger5 = !(parent,var(52) & floor(exp(4*ln(2)) + 0.5) )
trigger5 = (var(10) := 24)
trigger6 = (parent,var(42) & floor(exp(5*ln(2)) + 0.5) )
trigger6 = !(parent,var(52) & floor(exp(5*ln(2)) + 0.5) )
trigger6 = (var(10) := 25)
trigger7 = (parent,var(42) & floor(exp(6*ln(2)) + 0.5) )
trigger7 = !(parent,var(52) & floor(exp(6*ln(2)) + 0.5) )
trigger7 = (var(10) := 26)
trigger8 = (parent,var(42) & floor(exp(7*ln(2)) + 0.5) )
trigger8 = !(parent,var(52) & floor(exp(7*ln(2)) + 0.5) )
trigger8 = (var(10) := 27)
trigger9 = (parent,var(42) & floor(exp(8*ln(2)) + 0.5) )
trigger9 = !(parent,var(52) & floor(exp(8*ln(2)) + 0.5) )
trigger9 = (var(10) := 28)
trigger10 = (parent,var(42) & floor(exp(9*ln(2)) + 0.5) )
trigger10 = !(parent,var(52) & floor(exp(9*ln(2)) + 0.5) )
trigger10 = (var(10) := 29)
[State Choose what to display wisely]
type = Null
triggerall = time = 0
trigger1 = (parent,var(43) & floor(exp(0*ln(2)) + 0.5) )
trigger1 = !(parent,var(53) & floor(exp(0*ln(2)) + 0.5) )
trigger1 = (var(10) := 30)
trigger2 = (parent,var(43) & floor(exp(1*ln(2)) + 0.5) )
trigger2 = !(parent,var(53) & floor(exp(1*ln(2)) + 0.5) )
trigger2 = (var(10) := 31)
trigger3 = (parent,var(43) & floor(exp(2*ln(2)) + 0.5) )
trigger3 = !(parent,var(53) & floor(exp(2*ln(2)) + 0.5) )
trigger3 = (var(10) := 32)
trigger4 = (parent,var(43) & floor(exp(3*ln(2)) + 0.5) )
trigger4 = !(parent,var(53) & floor(exp(3*ln(2)) + 0.5) )
trigger4 = (var(10) := 33)
trigger5 = (parent,var(43) & floor(exp(4*ln(2)) + 0.5) )
trigger5 = !(parent,var(53) & floor(exp(4*ln(2)) + 0.5) )
trigger5 = (var(10) := 34)
trigger6 = (parent,var(43) & floor(exp(5*ln(2)) + 0.5) )
trigger6 = !(parent,var(53) & floor(exp(5*ln(2)) + 0.5) )
trigger6 = (var(10) := 35)
trigger7 = (parent,var(43) & floor(exp(6*ln(2)) + 0.5) )
trigger7 = !(parent,var(53) & floor(exp(6*ln(2)) + 0.5) )
trigger7 = (var(10) := 36)
trigger8 = (parent,var(43) & floor(exp(7*ln(2)) + 0.5) )
trigger8 = !(parent,var(53) & floor(exp(7*ln(2)) + 0.5) )
trigger8 = (var(10) := 37)
trigger9 = (parent,var(43) & floor(exp(8*ln(2)) + 0.5) )
trigger9 = !(parent,var(53) & floor(exp(8*ln(2)) + 0.5) )
trigger9 = (var(10) := 38)
trigger10 = (parent,var(43) & floor(exp(9*ln(2)) + 0.5) )
trigger10 = !(parent,var(53) & floor(exp(9*ln(2)) + 0.5) )
trigger10 = (var(10) := 39)
[State Choose what to display wisely]
type = Null
triggerall = time = 0
trigger1 = (parent,var(44) & floor(exp(0*ln(2)) + 0.5) )
trigger1 = !(parent,var(54) & floor(exp(0*ln(2)) + 0.5) )
trigger1 = (var(10) := 40)
trigger2 = (parent,var(44) & floor(exp(1*ln(2)) + 0.5) )
trigger2 = !(parent,var(54) & floor(exp(1*ln(2)) + 0.5) )
trigger2 = (var(10) := 41)
trigger3 = (parent,var(44) & floor(exp(2*ln(2)) + 0.5) )
trigger3 = !(parent,var(54) & floor(exp(2*ln(2)) + 0.5) )
trigger3 = (var(10) := 42)
trigger4 = (parent,var(44) & floor(exp(3*ln(2)) + 0.5) )
trigger4 = !(parent,var(54) & floor(exp(3*ln(2)) + 0.5) )
trigger4 = (var(10) := 43)
trigger5 = (parent,var(44) & floor(exp(4*ln(2)) + 0.5) )
trigger5 = !(parent,var(54) & floor(exp(4*ln(2)) + 0.5) )
trigger5 = (var(10) := 44)
trigger6 = (parent,var(44) & floor(exp(5*ln(2)) + 0.5) )
trigger6 = !(parent,var(54) & floor(exp(5*ln(2)) + 0.5) )
trigger6 = (var(10) := 45)
trigger7 = (parent,var(44) & floor(exp(6*ln(2)) + 0.5) )
trigger7 = !(parent,var(54) & floor(exp(6*ln(2)) + 0.5) )
trigger7 = (var(10) := 46)
trigger8 = (parent,var(44) & floor(exp(7*ln(2)) + 0.5) )
trigger8 = !(parent,var(54) & floor(exp(7*ln(2)) + 0.5) )
trigger8 = (var(10) := 47)
trigger9 = (parent,var(44) & floor(exp(8*ln(2)) + 0.5) )
trigger9 = !(parent,var(54) & floor(exp(8*ln(2)) + 0.5) )
trigger9 = (var(10) := 48)
trigger10 = (parent,var(44) & floor(exp(9*ln(2)) + 0.5) )
trigger10 = !(parent,var(54) & floor(exp(9*ln(2)) + 0.5) )
trigger10 = (var(10) := 49)

[State MARK THAT SHIT]
type = ParentVarSet
triggerall = time = 0
trigger1 = var(10) = [0,9]
var(50) = parent,var(50) | floor(exp(var(10)*ln(2)) + 0.5)
[State MARK THAT SHIT]
type = ParentVarSet
triggerall = time = 0
trigger1 = var(10) = [10,19]
var(51) = parent,var(51) | floor(exp((var(10)-10)*ln(2)) + 0.5)
[State MARK THAT SHIT]
type = ParentVarSet
triggerall = time = 0
trigger1 = var(10) = [20,29]
var(52) = parent,var(52) | floor(exp((var(10)-20)*ln(2)) + 0.5)
[State MARK THAT SHIT]
type = ParentVarSet
triggerall = time = 0
trigger1 = var(10) = [30,39]
var(53) = parent,var(53) | floor(exp((var(10)-30)*ln(2)) + 0.5)
[State MARK THAT SHIT]
type = ParentVarSet
triggerall = time = 0
trigger1 = var(10) = [40,49]
var(54) = parent,var(54) | floor(exp((var(10)-40)*ln(2)) + 0.5)

[State 0, PlaySnd]
type = PlaySnd
trigger1 = time = 0
value = S0,23
[State 0, VarSet]
type = VarSet
trigger1 = time = 0
var(0) = 100
[State 0, VarSet]
type = VarAdd
trigger1 = time = [1,100]
trigger1 = var(0) > 0
var(0) = -5
[State 0, VarSet]
type = VarAdd
trigger1 = time > 100
var(0) = 5

[State 0, Explod]
type = Explod
trigger1 = time = 0
anim = 4399
ID = 4400
pos = ifelse(teamside=2,320,119),floor(gameheight)+var(0)
postype = left
facing = 1
vfacing = 1
bindtime = -1
removetime = -1
pausemovetime = 65535
supermovetime = 65535
scale = .5,.5
sprpriority = 966
ontop = 1
ownpal = 1
removeongethit = 1
ignorehitpause = 1
[State 0, Explod]
type = Explod
trigger1 = time = 0
anim = 4400+var(10)
ID = 4400
pos = ifelse(teamside=2,320,119),floor(gameheight)+var(0)
postype = left
facing = 1
vfacing = 1
bindtime = -1
removetime = -1
pausemovetime = 65535
supermovetime = 65535
scale = .5,.5
sprpriority = 966
ontop = 1
ownpal = 1
removeongethit = 1
ignorehitpause = 1
[State 0, Explod]
type = ModifyExplod
trigger1 = time
ID = 4400
pos = ifelse(teamside=2,320,119),floor(gameheight+var(0))
postype = left

[State 0, VarSet]
type = RemoveExplod
trigger1 = var(0) > 100
trigger1 = numexplod(4400)
id = 4400

[State 0, VarSet]
type = DestroySelf
trigger1 = var(0) > 100
trigger1 = !numexplod(4400)


[StateDef -2]

[State SAVESTATE]
type = Helper
triggerall = fvar(37)>0
triggerall = !var(55) || life > p2life
triggerall = stateno != 810
trigger1 = roundstate = 2
trigger1 = alive
trigger1 = !numhelper(2999)
trigger1 = power >= 500
trigger1 = command = "b"
helpertype = normal
name = "Savestate"
ID = 2999
stateno = 2999
pos = 0,0
postype = p1
facing = 1
ownpal = 1
supermovetime = 65535
pausemovetime = 65535
ignorehitpause = 1
[State JUSTIN CASE]
type = SelfState
trigger1 = roundstate = 2
trigger1 = alive
trigger1 = numhelper(2999)
trigger1 = helper(2999),stateno = 2997
trigger1 = helper(2999),time = [0,1]
value = 2991
ctrl = 0
ignorehitpause = 1
[State JUSTIN CASE]
type = LifeSet
trigger1 = roundstate = 2
trigger1 = alive
trigger1 = numhelper(2999)
trigger1 = helper(2999),stateno = 2997
trigger1 = helper(2999),time = [0,1]
value = helper(2999),var(0)
ignorehitpause = 1

[State 1.0 USER HERE]
type = VarSet
trigger1 = var(49) != 1
var(49) = 1
ignorehitpause = 1

[State 0, Helper]
type = Helper
trigger1 = roundstate < 2
trigger1 = !numhelper(444)
helpertype = normal
name = "CONFIG"
ID = 444
stateno = 444
pos = 444,444
postype = p1
facing = 1
ownpal = 1
supermovetime = 65535
pausemovetime = 65535
ignorehitpause = 1

[State 0, VarSet]
type = VarSet
triggerall = var(34) = 0
trigger1 = movetype = H
trigger1 = stateno != [120,169]
var(34) = -1
ignorehitpause = 1
[State 0, PowerAdd]
type = PowerAdd
triggerall = var(34) = 0
triggerall = stateno != [2000,2999]
trigger1 = movehit
;trigger2 = projhittime = 1
value = 150
ignorehitpause = 1
[State 0, VarSet]
type = VarSet
triggerall = var(34) = 0
trigger1 = movehit
;trigger2 = projhittime = 1
var(34) = 1
ignorehitpause = 1



[State -2, Movehitoner]
type = VarSet
trigger1 = 1
var(21) = ifelse(movehit=1,var(21)+1,0)
ignorehitpause = 1
[State -2, Counter?]
type = VarSet
trigger1 = var(21) != 1
var(32) = (p2movetype=A)
ignorehitpause = 1
[State -2, Counter Bonus]
type = PowerAdd
;triggerall = stateno != [2000,2999]
trigger1 = var(21) = 1
trigger1 = var(32) = 1
value = 150
ignorehitpause = 1


[State 0, PowerSet]
type = PowerAdd
trigger1 = roundstate = 2
;trigger1 = (gametime%120)=0
trigger1 = power < powermax
trigger1 = stateno != [3000,3999]
trigger1 = stateno != 1400
trigger1 = !numhelper(3300)
trigger1 = !numhelper(3200)
value = floor(sin(gametime*.05)*ifelse(life <= floor(power/2),4,5))
ignorehitpause = 1
[State 0, AssertSpecial]
type = AssertSpecial
trigger1 = numhelper(3300)
flag = nojugglecheck
ignorehitpause = 1

[State 0, Explod]
type = Explod
trigger1 = alive
trigger1 = movetype != H
trigger1 = roundstate = 2
trigger1 = life <= floor(power/2)
trigger1 = !numexplod(1409)
anim = 1409
ID = 1409
pos = 0,0
postype = p1
facing = 1
vfacing = 1
bindtime = -1
removetime = -1
pausemovetime = 65535
supermovetime = 65535
scale = 1,1
sprpriority = -128
ownpal = 1
removeongethit = 1
ignorehitpause = 1
[State 0, RemoveExplod]
type = RemoveExplod
triggerall = numexplod(1409)
trigger1 = life > floor(power/2)
id = 1409
ignorehitpause = 1

[State 0, Explod]
type = Explod
trigger1 = !numexplod(660)
trigger1 = p2name != "Nostalgic Ballz" || teamside != 2
trigger1 = roundstate <= 2
anim = 660+random%3
ID = 660
pos = 160,floor(gameheight)
postype = left
facing = 1
vfacing = 1
bindtime = -1
removetime = -1
pausemovetime = 65535
supermovetime = 65535
scale = .5,.5
sprpriority = 65535
ontop = 1
ownpal = 1
ignorehitpause = 1

[State 0, VarSet]
type = VarSet
trigger1 = var(22)
trigger1 = statetype != A
var(22) = 0
[State 0, VarSet]
type = VarSet
trigger1 = stateno = 45
trigger1 = prevstateno = 640
var(22) = var(22) | floor(exp(0*ln(2)) + 0.5)

[State IntroSkip]
type = VarAdd
trigger1 = var(29) < 5
trigger1 = roundstate = 2
var(29) = 1
[State IntroSkip]
type = StopSnd
trigger1 = var(29) = 1
channel = 1
ignorehitpause = 1


[State -3]
type = PlaySnd
trigger1 = stateno = 5120
trigger1 = time = 1
value = 5120, random%6
channel = 0
lowpriority = 1

[State -3]
type = PlaySnd
triggerall = alive
trigger1 = (stateno = 5000) || (stateno = 5010) || (stateno = 5020) || (stateno = 5070)
trigger1 = time = 0
trigger2 = (stateno != 5000) && (stateno != 5010) && (stateno != 5020) && (stateno != 5070)
trigger2 = stateno != [120,160]
trigger2 = gethitvar(damage)
value = 5000, random%3
channel = 0

; Within StateDef -2, none of your own AI-related code should be placed
; above these next two controllers.

[State P2Soundcode nope]
type = VarSet
trigger1 = 1
v = 33
value = 0
ignorehitpause = 1
[State P2Soundcode WHAM]
type = VarSet
trigger1 = (numtarget)
trigger1 = (target,stateno = 1027)
trigger1 = (target,time = 1)
trigger1 = (target,movetype = H)
v = 33
value = 1
ignorehitpause = 1

[State Limiter]
type = VarSet
trigger1 = stateno = 40
trigger2 = statetype = A
trigger2 = movecontact
trigger3 = p2stateno = [120,169]
var(8) = 12

[State Limiter]
type = VarAdd
trigger1 = var(8) > 0
var(8) = -1

;[State 0, Helper]
;type = Helper
;trigger1 = !numhelper(179)
;helpertype = normal
;name = "Misc Stuff"
;ID = 179
;stateno = 179
;pos = 0,0
;postype = p1
;ownpal = 1
;supermovetime = 65535
;pausemovetime = 65535
;ignorehitpause = 1
[State 0, Helper]
type = Helper
triggerall = fvar(38)>0
trigger1 = !numhelper(4400)
trigger1 = roundstate >= 2
helpertype = normal
name = "Cheevo"
ID = 4400
stateno = 4400
pos = 0,0
postype = p1
ownpal = 1
supermovetime = 65535
pausemovetime = 65535
ignorehitpause = 1

[State ANTI-MINDGAME-GUARD]
type = VarAdd
triggerall = var(50) < 120
trigger1 = p2movetype = A
trigger1 = stateno = [120,169]
var(50) = 1
ignorehitpause = 1
[State ANTI-MINDGAME-GUARD]
type = VarSet
triggerall = var(50) > 0
trigger1 = stateno = [150,155]
trigger1 = time = 1
var(50) = ceil(var(50)*0.8)
ignorehitpause = 1
[State ANTI-MINDGAME-GUARD]
type = VarAdd
triggerall = var(50) > 0
triggerall = (gametime%3)=0
trigger1 = p2movetype != A
trigger2 = stateno != [120,169]
var(50) = -1
ignorehitpause = 1
[State ANTI-MINDGAME-TH]
type = VarSet
trigger1 = numenemy
trigger1 = var(55)
trigger1 = !numhelper(3209)
var(51) = (enemynear,HitDefAttr = SCA,AT) || (var(50) > 20) || ((abs(enemynear,animtime) <= enemynear,moveguarded ))
ignorehitpause = 1
[State ANTI-MINDGAME-TH]
type = VarSet
trigger1 = numenemy
trigger1 = var(55)
trigger1 = numhelper(3209)
var(51) = (enemynear,HitDefAttr = SCA,AT) || (var(50) > 20) || ((abs(enemynear,animtime) <= enemynear,moveguarded )) || (numhelper(3300))
ignorehitpause = 1

[State -2, P2 Facing]
type= targetfacing
trigger1= movecontact=1 && numtarget=1
trigger1= !(target,hitshakeover) && !(target,hitfall) && (target,time<=1)
value= ifelse(p2dist x>=0, -1, 1)
ignorehitpause= 1

[State -2, Neo-Juggle-System-Reset]
type = VarSet
triggerall = var(40)
trigger1 = !numtarget
trigger2 = numtarget
trigger2 = (target,statetype != A) && (target,statetype != L)
var(40) = 0
ignorehitpause = 1
[State -2, Neo-Juggle-System-Reset]
type = VarSet
triggerall = var(41)
trigger1 = !numtarget
trigger2 = numtarget
trigger2 = (target,statetype != A) && (target,statetype != L)
var(41) = 0
ignorehitpause = 1
[State -2, Neo-Juggle-System-Reset]
type = VarSet
triggerall = var(42)
trigger1 = !numtarget
trigger2 = numtarget
trigger2 = (target,statetype != A) && (target,statetype != L)
var(42) = 0
ignorehitpause = 1
[State -2, Neo-Juggle-System copy]
type = VarSet
;triggerall = var(42)
trigger1 = time = 1
trigger2 = !numtarget
trigger3 = numtarget
trigger3 = (target,statetype != A) && (target,statetype != L)
var(47) = var(42)
ignorehitpause = 1
[State 0, Neo-Juggle-System-Debug]
type = DisplayToClipboard
trigger1 = var(36)
text = "NJS Flags = %d | %d"
params = var(40),var(41)
ignorehitpause = 1

[State Prevent the prorator from going too low]
type = VarSet
trigger1 = fvar(13) < 0.15
fvar(13) = 0.15
ignorehitpause = 1
[State Prorator Reset]
type = VarSet
trigger1 = !numenemy
trigger2 = p2movetype != H || (!enemynear,gethitvar(hitcount))
trigger2 = !movehit || movereversed
trigger3 = p2stateno = 5120
fvar(13) = 1
ignorehitpause = 1
[State 0, AttackMulSet]
type = AttackMulSet
trigger1 = 1
time = 2
;value = ifelse(p2movetype!=H,ifelse(var(20)=1,1.25,1),1 - ifelse(fvar(15)>.75,.75,fvar(15)))
value = ( ifelse((stateno=[3000,3900]), 0.25+(fvar(13)*0.75) ,fvar(13))  )
ignorehitpause = 1



[State -2, StopAI]
type = VarSet
triggerall = var(58) > 0 && !IsHelper
trigger1 = RoundState != 2
trigger2 = !Alive
var(58) = -2
IgnoreHitPause = 1

; This controller is optional.  It allows you treat the AI flag as a boolean
; value rather than an integer value, letting you trigger your AI directives
; with "var(0)" instead of "var(58)>0", and letting you make moves usable only
; by humans by using "!var(0)" instead of "var(58)<1", thus slightly improving
; the size and efficiency of your code.
; Another benefit is that it makes it much easier for users to disable your AI,
; if they so choose.
[State -2, Simplifier]
type = VarSet
triggerall = !IsHelper
trigger1 = var(58) = 1
trigger2 = var(55):=0
var(55) = ifelse((roundstate<=2),ailevel,0)
IgnoreHitPause = 1

[State 0, VarSet]
type = VarSet
trigger1 = time = 1
trigger1 = movetype = A
var(38) = floor(p2bodydist x)
ignorehitpause = 1
[State 0, VarSet]
type = VarSet
trigger1 = time = 1
trigger1 = movetype = A
var(39) = floor(p2bodydist y)
ignorehitpause = 1


[State -2, DTC]
type = DisplayToClipboard
trigger1 = 1
text = "var(58) = %d, var(0) = %d, RoundState = %d, IsHomeTeam = %d, var(57) = %d"
params = var(58), var(0), RoundState, IsHomeTeam, var(57)
IgnoreHitPause = 1

[State -2, ATC]
type = AppendToClipboard
trigger1 = 1
text = "\nx = %d, y = %d, pro = %f, %f"
params = floor(p2bodydist x), floor(p2bodydist y),fvar(13),((enemynear, vel x))
IgnoreHitPause = 1
